server:
  port: 9091
# mysql数据源配置

spring:
  application:
    name: oauth2-resource
  resources:
    static-locations: classpath:/static/,classpath:/templates/,classpath:/pages/
  mvc:
    static-path-pattern: /resources/**
  thymeleaf:
    servlet:
      contentType: text/html; charset=utf-8
    cache: false
    mode: HTML
    encoding: UTF-8
    enabled: true
    prefix: classpath:/pages/
    suffix: .html
    check-template: false
    check-template-location: false
  main:
    allow-bean-definition-overriding: true

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}