server:
  port: 9090
# mysql数据源配置
db:
  dtype: mysql
spring:
  application:
    name: mq-rocketmq
  aop:
    auto: true
    proxy-target-class: true

  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    ##时间戳统一转换
    date-format: yyyy-MM-dd HH:mm:ss

######### RocketMQ ##########
rocketmq:
  name-server: 192.168.244.128:9876;192.168.244.129:9876;
  producer:
    group: drunkard
    send-message-timeout: 30000
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}-${server.port}.log
