ALTER TABLE GRP_ADDBOOK
   DROP FOREIGN KEY FK_GRP_ADDB_REFERENCE_REG_USER;

ALTER TABLE REG_USER_EXT
   DROP FOREIGN KEY FK_REG_USER_REFERENCE_DICT_REG;

ALTER TABLE REG_USER_EXT
   DROP FOREIGN KEY FK_REG_USER_REFERENCE_REG_USER;

ALTER TABLE REG_USER_EXT_HIST
   DROP FOREIGN KEY FK_REG_USER_REFERENCE_REG_USER;

ALTER TABLE REG_USER_HIS
   DROP FOREIGN KEY FK_REG_USER_REFERENCE_REG_USER;

DROP TABLE IF EXISTS DICT_REGION;


alter table GRP_ADDBOOK
   drop foreign key FK_GRP_ADDB_REFERENCE_REG_USER;

DROP TABLE IF EXISTS GRP_ADDBOOK;

DROP TABLE IF EXISTS REG_USER;


alter table REG_USER_EXT
   drop foreign key FK_REG_USER_REFERENCE_DICT_REG;

alter table REG_USER_EXT
   drop foreign key FK_REG_USER_REFERENCE_REG_USER;

DROP TABLE IF EXISTS REG_USER_EXT;


alter table REG_USER_EXT_HIST
   drop foreign key FK_REG_USER_REFERENCE_REG_USER;

DROP TABLE IF EXISTS REG_USER_EXT_HIST;


alter table REG_USER_HIS
   drop foreign key FK_REG_USER_REFERENCE_REG_USER;

DROP TABLE IF EXISTS REG_USER_HIS;

CREATE TABLE DICT_REGION
(
   DICT_REGION_ID       BIGINT(13) NOT NULL  COMMENT '',
   REGION_NAME          VARBINARY(20)  COMMENT '',
   REGION_CODE          VARBINARY(5)  COMMENT '',
   UP_REGION_CODE       VARBINARY(5)  COMMENT '',
   STATUS               INT(1)  COMMENT '',
   PRIMARY KEY (DICT_REGION_ID)
);

CREATE TABLE REG_USER
(
   U_ID                 BIGINT(13) NOT NULL  COMMENT '',
   NICK_NAME            VARBINARY(20) NOT NULL  COMMENT '',
   U_CODE               VARBINARY(20)  COMMENT '',
   U_MOBILE             VARBINARY(11)  COMMENT '',
   EMAIL                VARBINARY(30)  COMMENT '',
   U_PWD                VARBINARY(50)  COMMENT '',
   SAT                  VARBINARY(10)  COMMENT '',
   STATUS               CHAR(1)  COMMENT '',
   PRIMARY KEY (U_ID)
);

CREATE TABLE GRP_ADDBOOK
(
   GRP_ADDBOOK_ID       BIGINT(13) NOT NULL  COMMENT '',
   U_ID                 BIGINT(13)  COMMENT '',
   FD_GRP               BLOB  COMMENT '好友的Set集合，JSO序列化',
   STATUS               INT(1)  COMMENT '',
   PRIMARY KEY (GRP_ADDBOOK_ID)
);

CREATE TABLE REG_USER_EXT
(
   U_REG_USER_EXT_ID    BIGINT(13) NOT NULL  COMMENT '',
   DICT_REGION_ID       BIGINT(13)  COMMENT '',
   U_ID                 BIGINT(13)  COMMENT '',
   GENDER               CHAR(1)  COMMENT '',
   BIRTHDAY             DATE  COMMENT '',
   LAST_ACTIVE_DATE     DATETIME  COMMENT '',
   PRIMARY KEY (U_REG_USER_EXT_ID)
);

CREATE TABLE REG_USER_EXT_HIST
(
   REG_USER_HIS_ID      BIGINT(13) NOT NULL  COMMENT '',
   U_REG_USER_EXT_ID    BIGINT(13)  COMMENT '',
   PRIMARY KEY (REG_USER_HIS_ID)
);

CREATE TABLE REG_USER_HIS
(
   REG_USER_HIS_ID      BIGINT(13) NOT NULL  COMMENT '',
   U_ID                 BIGINT(13) NOT NULL  COMMENT '',
   NICK_NAME            VARBINARY(20) NOT NULL  COMMENT '',
   U_CODE               VARBINARY(20)  COMMENT '',
   U_MOBILE             VARBINARY(11)  COMMENT '',
   EMAIL                VARBINARY(30)  COMMENT '',
   U_PWD                VARBINARY(50)  COMMENT '',
   SAT                  VARBINARY(10)  COMMENT '',
   STATUS               CHAR(1)  COMMENT '',
   PRIMARY KEY (REG_USER_HIS_ID)
);
