server:
  port: 9090

db:
  dtype: oracle
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.10.10.10:1521:tycata
    username: uom
    password: scuom_0824
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=6000
      login-username: admin
      login-password: 123456
  aop:
    auto: true
    proxy-target-class: true

  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    ##时间戳统一转换
    date-format: yyyy-MM-dd HH:mm:ss

ip2region:
  enabled: true
  dbfile: ipdb/ip2region.db
######### mybatis ##########
mybatis:
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
  mapperLocations: classpath:mapper/**/*.xml

######### 分页插件 ##########
pagehelper:
  helper-dialect: ${db.dtype}
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

