server:
  port: 9090
# mysql数据源配置

spring:
  application:
    name: oauth2-server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.244.128:3306/area20?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=6000
      login-username: admin
      login-password: 123456
  resources:
    static-locations: classpath:/static/,classpath:/templates/,classpath:/pages/
  mvc:
    static-path-pattern: /resources/**
  thymeleaf:
    servlet:
      contentType: text/html; charset=utf-8
    cache: false
    mode: HTML
    encoding: UTF-8
    enabled: true
    prefix: classpath:/pages/
    suffix: .html
    check-template: false
    check-template-location: false
  main:
    allow-bean-definition-overriding: true
# mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}